### ISSUE TITLE
Missing Peak List File [read Proteome Discoverer export]

### ISSUE THREAD

**Issue by rchill14** [Rappsilber-Laboratory/xiView_container#17]
We're working with data searched by xlinkx in Proteome Discoverer. Direct exports utilizing any combination of mgf/mzML for peak list do no work here (or zipped), giving the same error message. We also tried searching this without the peak list file, only for it to fail after "updating our ions". The peak list error message is shown below. 

Thanks!

Ryan

log id: o2sif9l5op3cbmpv8qafcfuqc3_1536277910.log (include this in the github issue)
error type: Error
message: Missing peak list file: ../uploads/o2sif9l5op3cbmpv8qafcfuqc3/20180902_AIssaian_Pentamer_DSSO_MS2-(1).zip_unzip/20180902_AIssaian_Pentamer_DSSO_MS2-(1).mzML
id: undefined

**Comment by rchill14** [comment]
Alternatively with a different file:
log id: o2sif9l5op3cbmpv8qafcfuqc3_1536340266.log (include this in the github issue)
error type: Error
message: ascii
id: undefined

**Comment by colin-combe** [comment]
the first case was maybe the mgf peak list being supplied when the identification file referred to the mzml file. 

the second case was maybe the mzml file being supplied but there was a problem reading it. We will update the parser so it either works or provides a meaningful message about what went wrong.

I think reading Proteome Discoverer mzIdentML export won't work because it doesn't export cross-linked peptides in mzIdentML (it exports mzIdentML v1.1).

The xiNET CSV export from Proteome Discoverer possibly does work but is missing the information to make the connection the peak list files/spectra (but you should be able to look at the network in 2d & 3d).

**Comment by rchill14** [comment]
Hi Colin,

  Hope you enjoyed some time off and thank you for your explanations. So
from what I gather, there really isn't a good way to get xlinkx data from
Proteome Discoverer (with spectra) to work here? The 2d and 3D networks are
certainly helpful though, so thank you for your efforts here!

Cheers,

Ryan

**Comment by colin-combe** [comment]
>  So from what I gather, there really isn't a good way to get xlinkx data from Proteome Discoverer (with spectra) to work here?

From looking at the tables in the supplementary data of papers using xlinkx, I think xlinkx might have its own csv format which contains the info needed and wouldn't be too hard to support. I tried to install xlinkx to check but ran into some problems (I'll try again / take it take up with them).

If there is some xlinkx CSV format containing the peak list file name and scan id then I can maybe make it work here. If there is, could you provide an example please?

**Comment by colin-combe** [comment]
>  So from what I gather, there really isn't a good way to get xlinkx data from Proteome Discoverer (with spectra) to work here?

Yes, that's right.

You can read the CSV export to get 2d and 3d networks, but there isn't a way to link the supporting spectra.

Ideally, PD would implement mzIdentML v1.2 export

**Comment by colin-combe** [comment]
I think PD does now have mzIdentML 1.2.0 export
