### ISSUE TITLE
google recaptcha issues

### ISSUE THREAD

**Issue by colin-combe** [Rappsilber-Laboratory/xiView_container#29]
in certain browser/OS combos google recaptcha is not appearing so people cannot create acount

**Comment by martingraham** [comment]
If they say which combinations we could investigate using browserstack

**Comment by colin-combe** [comment]
it was firefox on linux

**Comment by martingraham** [comment]
Hang on, no we can't because browserstack doesn't support linux

https://twitter.com/browserstack/status/942643437219786752?lang=en



It works on the latest firefox (60.7) on windows 7, so it's either an OS issue or something has been set in the particular instance of the browser (tracking protection) - https://meta.stackexchange.com/questions/312941/captchas-not-appearing-browser-problem

**Comment by colin-combe** [comment]
it works for me on FireFox on linux,
you're right its probably tracking protection or something (@grandrea )
think this can be closed
