### ISSUE TITLE
Cannot concatenate 'str' and 'int' objects

### ISSUE THREAD

**Issue by SarahJoergensen** [Rappsilber-Laboratory/xiView_container#63]
I exported my results from MeroX, but get the following error. 
>  cannot concatenate 'str' and 'int' objects
![Screenshot_1](https://user-images.githubusercontent.com/58903828/70861079-d7a11600-1f29-11ea-9a80-bdee837223b5.png)
log id: or5ciab0qratqbbbrrupi816v1_1576403886.log

**Comment by colin-combe** [comment]
ok, thanks for report.

**Comment by colin-combe** [comment]
I think there is a problem with the CSV file you tried to upload.

Try opening it in a spreadsheet program - are there more columns of data than there are column headings?

If so, this is because there is a extra, not enclosed by quotes, comma in one of your data fields. 

Look at it again in a speadsheet program - does it have the right thing in the 'rank' column?

**Comment by SarahJoergensen** [comment]
Hi Colin,
Thank you for your help! You are right about the extra column of data
compared to column headings.
Is it a wrong type of .csv I am using?
I have tried to save it as different .csv file types (comma-Delimited,
Macintosh, and MS-DOS).
When I use the MS-DOS I get this error instead.
Best regards,
Sarah

Den tir. 17. dec. 2019 kl. 16.34 skrev Colin <notifications@github.com>:

**Comment by colin-combe** [comment]
as far as I can tell, the problem is that your ScanId attributes contain commas, breaking the CSV file.

The ScanId also contains quote marks, complicating dealing with the comma by enclosing the whole ScanId with quotes.

I think it might work if the comma in ScanId is preceded by a backslash.

> Is it a wrong type of .csv I am using?

I'm not sure where this file came from. If its direct output from MeroX then I would take this up with the MeroX team. If you've created it yourself, you have some fiddling around to do regarding escaping the comma.  

The best thing would be if MeroX output mzIdentML, which is read by xiVIEW and is the standard for the data.

Even if you get the CSV files working, they are missing some of the information needed to provide you with annotated spectra. For example, the modification masses, which you will need to enter manually but which would be included in the mzIdentML file.

**Comment by colin-combe** [comment]
on reflection, I'm maybe overstating it when I say "mzIdentML is the standard for the data". It is an existing, PSI endorsed standard but the crosslinking field has yet to reach consensus on what to use.

**Comment by colin-combe** [comment]
exporting the file from your spreadsheet program with enclosing quotation marks around the values might fix this (if it automatically escapes the other quotation marks)

**Comment by colin-combe** [comment]
I think this could be closed because its a problem with your CSV?

Also, are you sure Merox doesn't export mzIdentML?
