### ISSUE TITLE
Import of XiFDR.csv data in XiVIEW

### ISSUE THREAD

**Issue by wendscheck** [Rappsilber-Laboratory/xiView_container#68]
Hi, 
like to import my >filename<Xi1.7.0_PSM_xiFDR1.4.1.csv in XiVIEW, but have several issues with that. I'm choosing this table, cause i have to do some python-based filtering between export from XiFDR and import in XiVIEW. My data looks exactly like the example csv data (PolII_XiVersion1.6.742_PSM_xiFDR1.1.27.csv downloaded from https://xiview.org/xiNET_website/upload.php) and during the upload i get no warnings or errors. But, i have a set of links which should be displayed as homomultimeric links, but they are not and are displayed as intra-links instead. I recognized that for those links i have two semicolon separated values in the column 'PepPos' (displayed by XiView after click on the link), which makes no sense to me and could be one reason for this issue. When i look up the column 'PepPos1' and 'PepPos2' in my csv manually i can't find any abnormal features. Do you have any idea how to fix this?

**Comment by colin-combe** [comment]
> i have a set of links which should be displayed as homomultimeric links, but they are not and are displayed as intra-links instead. I recognized that for those links i have two semicolon separated values in the column 'PepPos' (displayed by XiView after click on the link), which makes no sense to me and could be one reason for this issue.

Yes, I think you have correctly intuited the reason.

The semicolon seperated values in the PepPos columns indicate that the position of the peptide is ambiguous, that the peptide occurs in more than one location in your search sequences. (Each semicolon separated value is a different possible position.)

If these peptides do not occur in more than one place and are being incorrectly marked as ambiguous then something has gone wrong and please let us know.

Crosslinks with ambiguous positioned peptides do not get displayed as homomultimers because generally if they are ambiguous they don't *definitely* overlap. 

Having said that there are some funny edge cases, that aren't necessarily dealt with properly, like a case where they are ambiguous but all alternatives definitely do overlap. To be honest, last time I looked at this I couldn't come up with code that correctly dealt with all the edge cases I could think of.

I hope this makes some sort of sense - if you want you can post a few example lines from the CSV file that have this funny behaviour and we can look in more detail at what it *is* doing as compared to what it *should* do ,
cheers,
colin

**Comment by colin-combe** [comment]
it was like you thought.

there was a bug introducing the two values with a semi-colon between them

i think it should be fixed now, let me know if not

the bug was in the parser on the server side, not the javascript that runs in the browser, so you will have to upload your data again for it to be fixed
