### ISSUE TITLE
Error loading file Not Found. Please check the PDB file or code is correct.

### ISSUE THREAD

**Issue by ezbie** [Rappsilber-Laboratory/xiView_container#76]
This error occurs whenever I attempt to load a PDB file, no matter which file is used. The upload had previously been working with the same PDB files but now no longer works

**Comment by colin-combe** [comment]
I think this is when entering the 4 character PDB code and letting xiVIEW fetch the file from PDB?

I think its broken because of changes to the PDB web service (which I was forewarned about).

It should be that if you download the file and then upload it as a local pdb file then it will work? Could you check please?
thanks,
Colin

**Comment by colin-combe** [comment]
yep, think it should work if downloaded and uploaded as local PDB file. Its inconvenient though, will need to fix

**Comment by ezbie** [comment]
Yes it works with download

**Comment by colin-combe** [comment]
I think that's fixed now,
cheers,
col
