### ISSUE TITLE
Uploading data failed (csv, fasta, zipped mgf)

### ISSUE THREAD

**Issue by gieses** [Rappsilber-Laboratory/xiView_container#77]
Hi,

I tried to upload a fasta, xiFDR CSM file and recalibrated mgfs in a zip file.

log id: 93b61gp4iro13oor5n4ohc7020_1605087237.log (include this in the github issue)
error type: Error
message: 'numpy.float64' object has no attribute 'lower'
id: undefined

Its not urgent since I dont really need the spectra to be displayed.

**Comment by colin-combe** [comment]
hi sven - could you share the files with me on slack please?

**Comment by GiuliaS89** [comment]
Hi,

I am having the same problem when uploading .csv file:

log id: c9oplnnn9jpvadok6ggond06f1_1620992376.log (include this in the github issue)
error type: Error
message: Required csv column abspos1 missing
id: undefined

**Comment by colin-combe** [comment]
Hi,

I think this is a different issue  - it has a more meaningful error message :-
`message: Required csv column abspos1 missing`

it is saying that your file doesn't conform to any of the formats described at https://xiview.org/xiNET_website/csvFormats.php

It could still be that the problem is on our side - if you share the CSV file with me I can check whats happening. You can post it here or email it too me (colin.combe@ed.ac.uk)

@gieses - we dealt with `numpy.float64' object has no attribute 'lower` did we?
