### ISSUE TITLE
Empty view if mzIdentML file contains protein sequences (public website)

### ISSUE THREAD

**Issue by vrkosk** [Rappsilber-Laboratory/xiView_container#85]
Upload an mzIdentML 1.2 file where protein sequences are encoded like:

```
    <DBSequence id="DBSeq_1_LYSC_CHICK" searchDatabase_ref="SDB_SwissProt" accession="LYSC_CHICK" >
      <Seq>MRSLLILVLCFLPLAALGKVFGRCELAAAMKRHGLDNYRGYSLGNWVCAAKFESNFNTQATNRNTDGSTDYGILQINSRWWCNDGRTPGSRNLCNIPCSALLSSDITASVNCAKKIVSDGNGMNAWVAWRNRCKGTDVQAWIRGCRL</Seq>
      <cvParam accession="MS:1001088" name="protein description" cvRef="PSI-MS" value="Lysozyme C OS=Gallus gallus OX=9031 GN=LYZ PE=1 SV=1" />
    </DBSequence>
```

xiVIEW doesn't report any warnings or errors on upload. However, no proteins are shown and it seems all peptide matches are thresholded out of existence (e.g. "0 out of 8").

If I delete the <Seq> elements and re-upload. proteins are shown fine.

**Comment by colin-combe** [comment]
Hi Ville, 

are you able to share the whole mzIdentML file?

cheers,
Colin

**Comment by colin-combe** [comment]
(just tested other mzid files do still work with Seq included)

**Comment by vrkosk** [comment]
I'm wrong, it's actually caused by the presence of sameset proteins, not protein sequences. Attached are mzIdentML exports of the example disulfide search from a Mascot development version. Each file validates fine against the schema, and the mzIdentML validator version 1.4.35 reports no errors.

F002553.mzid has default settings (no samesets, no protein sequences) and works OK.

F002553_seqs.mzid has protein sequences and works OK.

F002553_samesets.mzid has sameset proteins and xiVIEW shows no proteins at all.

F002553_samesets_and_seqs.mzid has sameset proteins and protein sequences and xiVIEW shows no proteins at all (this is the file I initially used).

[F002553_seqs.zip](https://github.com/Rappsilber-Laboratory/xiView_container/files/8032893/F002553_seqs.zip)
[F002553_samesets.zip](https://github.com/Rappsilber-Laboratory/xiView_container/files/8032894/F002553_samesets.zip)
[F002553_samesets_and_seqs.zip](https://github.com/Rappsilber-Laboratory/xiView_container/files/8032895/F002553_samesets_and_seqs.zip)
[F002553.zip](https://github.com/Rappsilber-Laboratory/xiView_container/files/8032896/F002553.zip)

**Comment by colin-combe** [comment]
It might be that things are working OK, but you're encountering a confusing bit of xiVIEW behaviour.

People asked to have the self links unselected by default for large searches (>50 proteins). In retrospect, this was a bad idea and we're changing it back.

I think the  'samesets' mzId files do have more than 50 proteins, even though only one of them is crosslinked;
so that "Self" checkbox in the bottom filter bar is unchecked? If you check it it your 8 cross-links should come back?

The linear identifications (uncrosslinked identifications) aren't displayed on the network visualisation page (it would be good to have them there as an indication of sequence coverage). There is another way to look at the linears (the easily missed "Spectra Only" link on the history page), but that doesn't seem to be working correctly. I'll need to  look into it...

**Comment by vrkosk** [comment]
"Self" was indeed unchecked and checking it displays the crosslinks. I agree it's confusing when only one protein in the file has intralinks and there are no interlinks.

**Comment by colin-combe** [comment]
yes, its super confusing

**Comment by vrkosk** [comment]
Seems to be fixed. I uploaded the same file with sameset proteins included. The file has one intralinked protein and 87 proteins with no links, and now intralinks are shown by default after uploading the file.
